version: '3.9'

services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment:
            - ENVIRONMENT=development
            - SECRET_KEY=kcp6i$$21ck_+9928-&d+kv$$x5n!&ab7h2u6h!2nwq^(v=zhu6!
            - DEBUG=1
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres:11
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres