# Generated by Django 3.1.6 on 2021-02-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20210206_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='id',
        ),
        migrations.AddField(
            model_name='channel',
            name='yt_id',
            field=models.CharField(default='id', max_length=255, primary_key=True, serialize=False),
        ),
    ]
