# Generated by Django 3.1.6 on 2021-02-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20210206_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='yt_id',
            new_name='id',
        ),
    ]
